### ISSUE TITLE
这个项目和vue-super-flow,有什么不一样呢

### ISSUE THREAD

**Issue by martinwithyou** [caohuatao/vue3-super-flow#1]
这个项目和vue-super-flow,有什么不一样呢

**Comment by caohuatao** [comment]
vue3.0 版本的

**Comment by martinwithyou** [comment]
> vue3.0 版本的

加油，你可以的，
你的这个版本的流程图，
比很多历史悠久的流程图，
大企业的开源流程图，
都要好用，
用户体验都要好

**Comment by martinwithyou** [comment]
> vue3.0 版本的

建议你可以暴露更多接口给用户，
方便用户做定制化开发。。。。
你觉得呢？
