### ISSUE TITLE
请问如何使用啊, 就像vue2.x版本的doc一样,  没安装部分实在不知道如何弄啊, 求助大佬

### ISSUE THREAD

**Issue by zhyusgethup** [caohuatao/vue3-super-flow#2]
请问如何使用啊, 就像vue2.x版本的doc一样, 至少有安装部分我才能看懂

**Comment by caohuatao** [comment]
vue3版本的，还没时间开发。所以是用不了的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhyusgethup ***@***.***&gt;
发送时间: 2021年5月27日 11:19
收件人: caohuatao/vue3-super-flow ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[caohuatao/vue3-super-flow] 请问如何使用啊, 就像vue2.x版本的doc一样,  没安装部分实在不知道如何弄啊, 求助大佬 (#2)





 
请问如何使用啊, 就像vue2.x版本的doc一样, 至少有安装部分我才能看懂

**Comment by zhyusgethup** [comment]
好的 谢谢
